# Generated by Django 3.2.5 on 2021-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='Value',
            field=models.CharField(max_length=15),
        ),
    ]
