# Generated by Django 3.2.4 on 2021-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_alter_chart_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='streamgraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('Amanda', models.IntegerField()),
                ('Ashley', models.IntegerField()),
                ('Betty', models.IntegerField()),
                ('Deborah', models.IntegerField()),
                ('Dorothy', models.IntegerField()),
                ('Helen', models.IntegerField()),
                ('Linda', models.IntegerField()),
                ('Patricia', models.IntegerField()),
            ],
        ),
    ]
